FROM node:18-bookworm

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY opulus-core/package.json ./opulus-core/
COPY opulus-backend/package.json ./opulus-backend/
COPY opulus-frontend/package.json ./opulus-frontend/
COPY opulus-webhooks/package.json ./opulus-webhooks/
COPY opulus-tests/package.json ./opulus-tests/

RUN pnpm install --frozen-lockfile
