import { RouterProvider, createRouter } from '@tanstack/react-router';

// Import the generated route tree (auto-generated by TanStack Router Vite plugin)
import { routeTree } from './routeTree.gen';

// Create a new router instance
const router = createRouter({ routeTree });

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }

  /** What a route can set for the layout around it, e.g. the page title. */
  interface StaticDataRouteOption {
    title?: string;
    /** The parent section shown before the title, e.g. "Settings". */
    section?: string;
  }
}

function App() {
  return <RouterProvider router={router} />;
}

export default App;
